# title of website
title: navigation

# description of website
description: ggbond-cc's navigation site

# favicon of website
favicon: "https://github.com/ggbond-cc.png?size=40"

# your website url
url: https://ggbond-cc.github.io/navigation/

# github profile url
github: "https://github.com/ggbond-cc"

# footer message
footer: © 2021-2021 @ggbond-cc

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: NASTool
          description: nastool
          url: http://192.168.20.175:13000/
        - name: m-team
          description: m-team
          url: https://kp.m-team.cc/
        - name: qbittorent
          description: qbittorent
          url: http://192.168.20.175:9901
        - name: Emby
          description: Emby
          url: http://192.168.20.175:8096
        - name: dic-music
          description: dicmusic
          url: https://dicmusic.club  
    - name: HOME
      sites:
        - name: miWifi
          description: miWifi
          url: http://192.168.20.1
        - name: openWrt
          description: oepnWrt
          url: http://192.168.20.176
        - name: promox
          description: promox
          url: https://192.168.20.208:8006
        - name: openMediaVault
          description: openMediaVault
          url: http://192.168.20.175
       - name: qbittorent
          description: qbittorent
          url: http://192.168.20.175:9901
        - name: Emby
          description: Emby
          url: http://192.168.20.175:8096
    - name: PT
        - name: m-team
          description: m-team
          url: https://kp.m-team.cc/
        - name: pttime
          description: pttime
          url: https://www.pttime.org/
        - name: dic-music
          description: dicmusic
          url: https://dicmusic.club        
        - name: tccf
          description: tccf
          url: https://et8.org/
